import { useState, useEffect } from "react";
import Head from "next/head";
import { fetchTodo, addTodo, deleteTodo, editTodo } from "./api/todo";
import form from "@/form";
import EditModal from "@/components/edit";

export default function Home() {
  const [newTodo, setNewTodo] = useState("");
  const [alltodos, setAlltodos] = useState([]);
  const [info, setInfo] = useState("");
  const [modal, openModal] = useState(false);

  useEffect(() => {
    const fetchData = async () => {
      const data = await fetchTodo();
      setAlltodos(data);
    };

    fetchData();
  }, []);

  const handleInputChange = (event) => {
    setNewTodo(event.target.value);
  };

  const refresh = async () => {
    const updatedData = await fetchTodo();
    setAlltodos(updatedData);
  };

  const handleAddTodo = async () => {
    await addTodo({ ...form, title: newTodo });
    setNewTodo("");
    refresh();
  };

  const handleDeleteTodo = async (id) => {
    await deleteTodo(id);
    refresh();
  };

  const handleEditTodo = (info) => {
    setInfo(info);
    openModal(true);
  };

  const toggleModal = () => {
    openModal(!modal);
  };

  return (
    <>
      <Head>
        <title>To-do App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {modal && <EditModal props={info} closeModal={toggleModal} refresh={refresh}/>}
      <div className="container">
        <h1>Add to do</h1>
        <div className="input-group mb-3">
          <input
            type="text"
            className="form-control"
            value={newTodo}
            onChange={handleInputChange}
            placeholder="Enter a new todo"
          />
          <div className="input-group-append">
            <button className="btn btn-primary" onClick={handleAddTodo}>
              Add Todo
            </button>
          </div>
        </div>
        <ul className="list-group">
          {alltodos.map((todo) => (
            <li
              key={todo.id}
              className="list-group-item d-flex justify-content-between align-items-center"
            >
              <div className="form-check">
              {todo.completed ? <>&#10004;</> : null}
                <label className="form-check-label">{todo.title}</label>
              </div>
              <div className="d-flex gap-2">
                <button
                  className="btn btn-info mr-2"
                  onClick={() => handleEditTodo(todo)}
                >
                  Edit
                </button>
                <button
                  className="btn btn-danger"
                  onClick={() => handleDeleteTodo(todo.id)}
                >
                  Delete
                </button>
              </div>
            </li>
          ))}
        </ul>
      </div>
    </>
  );
}
