import { useState, useEffect } from "react";
import Head from "next/head";
import { fetchTodo, addTodo, deleteTodo } from "./api/todo";
import form from "@/form";

export default function Home() {
  const [newTodo, setNewTodo] = useState("");
  const [alltodos, setAlltodos] = useState([]);

  useEffect(() => {
    const fetchData = async () => {
      try {
        const data = await fetchTodo();
        setAlltodos(data);
      } catch (error) {
        console.error("Failed to fetch todos:", error);
      }
    };

    fetchData();
  }, []);

  const handleInputChange = (event) => {
    setNewTodo(event.target.value);
  };

  const refresh = async () => {
    try {
      const updatedData = await fetchTodo();
      setAlltodos(updatedData);
    } catch (error) {
      console.error("Failed to refresh todos:", error);
    }
  };

  const handleAddTodo = async () => {
    try {
      await addTodo({ ...form, title: newTodo });
      setNewTodo("");
      refresh();
    } catch (error) {
      console.error("Failed to add todo:", error);
    }
  };

  const handleDeleteTodo = async (id) => {
    try {
      await deleteTodo(id);
      refresh();
    } catch (error) {
      console.error("Failed to delete todo:", error);
    }
  };

  const completeTask = async (id) => {

  }

  return (
    <>
      <Head>
        <title>To do app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="pb-2">
        <input
          type="text"
          value={newTodo}
          onChange={handleInputChange}
          placeholder="Enter a new todo"
        />
        <button onClick={handleAddTodo}>Add Todo</button>
      </div>
      <ul>
        {alltodos.map((todo) => (
          <li key={todo.id} className="pb-2">
            <input
              type="checkbox"
              checked={todo.completed}
              onChange={() => completeTask(todo.id)}
            />
            {todo.title}{" "}
            <button onClick={() => handleDeleteTodo(todo.id)}>Delete</button>
          </li>
        ))}
      </ul>
    </>
  );
}
